"""make phone number nullable

Revision ID: 96555de69066
Revises: b99e413a24df
Create Date: 2026-10-07 08:42:46.216787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96555de69066'
down_revision: Union[str, Sequence[str], None] = 'b99e413a24df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
