"""update product listing schema

Revision ID: b99e413a24df
Revises: 7ffef9b3c62b
Create Date: 2026-09-17 22:03:46.892280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b99e413a24df'
down_revision: Union[str, Sequence[str], None] = '7ffef9b3c62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_file',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.drop_table('product_image')
    op.add_column('product', sa.Column('delivery_options', sa.String(length=30), nullable=False))
    op.alter_column('product', 'sold_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'sold_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('product', 'delivery_options')
    op.create_table('product_image',
    sa.Column('image_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('object_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('product_image_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('product_image_pkey'))
    )
    op.drop_table('product_file')
    # ### end Alembic commands ###
